#!/bin/sh -f
# Configure wmii

# Configuration Variables
MODKEY=Mod4
SMODKEY=$MODKEY-
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Colors tuples: "<text> <background> <border>"
WMII_NORMCOLORS='#888888 #222222 #333333'
WMII_FOCUSCOLORS='#ffffff #285577 #4c7899'
WMII_CMDMODE='#FF6633'
WMII_BACKGROUND='#333333'
WMII_FONT='fixed'

WMII_DNORMCOLORS='#888888 #222222 #333333'
WMII_DFOCUSCOLORS='#ffffff #285577 #4c7899'
WMII_CMDFOCUSCOLORS='#ff7700 #111111 #ff7700'
WMII_CMDNORMCOLORS='#000000 #ff7700 #666666'

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
WMII_MENU="dmenu -b -fn '$WMII_FONT' -nf '$1' -nb '$2' -sf '$4' -sb '$5'"
WMII_9MENU="wmii9menu -font '$WMII_FONT' -nf '$1' -nb '$2' -sf '$4' -sb '$5' -br '$6'"
WMII_TERM="x-terminal-emulator"

# Column Rules
wmiir write /colrules <<!
/.*/ -> 50+50
!

# Tagging Rules
wmiir write /tagrules <<!
/XMMS.*/ -> ~
/MPlayer.*/ -> ~
/.*/ -> sel
/.*/ -> 1
!

# Status Bar Info
status() {
	echo -n $(uptime | sed 's/.*://; s/,//g') '|' $(date)
}

# Event processing
#  Processed later by `wmiiloop' and evaled.
#  Duplicate the eval line and replace 'eval' with 'echo' for details.
eventstuff() {
	cat <<'!'
	# Events
	Event Start
		case "$1" in
		wmiirc)
			exit;
		esac
	Event Key
		fn=$(echo "$@" | sed 's/[^a-zA-Z_0-9]/_/g')
		Key_$fn "$@"
	Event CreateTag
		echo "$WMII_NORMCOLORS" "$@" | wmiir create "/lbar/$@"
	Event DestroyTag
		wmiir remove "/lbar/$@"
	Event FocusTag
		wmiir xwrite "/lbar/$@" "$WMII_FOCUSCOLORS" "$@"
	Event UnfocusTag
		wmiir xwrite "/lbar/$@" "$WMII_NORMCOLORS" "$@"
	Event UrgentTag
		shift
		wmiir xwrite "/lbar/$@" "*$@"
	Event NotUrgentTag
		shift
		wmiir xwrite "/lbar/$@" "$@"
	Event LeftBarClick
		shift
		wmiir xwrite /ctl view "$@"
	# Actions
	Action quit
		wmiir xwrite /ctl quit
	Action exec
		wmiir xwrite /ctl exec "$@"
	Action rehash
		proglist $PATH >$progsfile
	Action status
		set +xv
		if wmiir remove /rbar/status 2>/dev/null; then
			sleep 2
		fi
		echo "$WMII_NORMCOLORS" | wmiir create /rbar/status
		while status | wmiir write /rbar/status; do
			sleep 1
		done
	Event ClientMouseDown
		client=$1; button=$2
		case "$button" in
		3)
			do=$(eval $WMII_9MENU -initial "${menulast:-SomeRandomName}" Nop Delete Fullscreen)
			case "$do" in
			Delete)
				wmiir xwrite /client/$client/ctl kill;;
			Fullscreen)
				wmiir xwrite /client/$client/ctl Fullscreen on;;
			esac
			menulast=${do:-"$menulast"}
		esac
	# Key Bindings
	Key SMODKEYControl-t
		case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
		0|1)
			echo -n $Keys | tr ' ' '\012' | wmiir write /keys
			wmiir xwrite /ctl grabmod $MODKEY;;
		*)
			wmiir xwrite /keys SMODKEYControl-t
			wmiir xwrite /ctl grabmod Mod3;;
		esac
	Key SMODKEYspace
		wmiir xwrite /tag/sel/ctl select toggle
	Key SMODKEYd
		wmiir xwrite /tag/sel/ctl colmode sel default
	Key SMODKEYs
		wmiir xwrite /tag/sel/ctl colmode sel stack
	Key SMODKEYm
		wmiir xwrite /tag/sel/ctl colmode sel max
	Key SMODKEYa
		Action $(actionlist | eval $WMII_MENU) &
	Key SMODKEYp
		sh -c "$(eval $WMII_MENU <$progsfile)" &
	Key SMODKEYt
		wmiir xwrite /ctl "view $(tagsmenu)" &
	Key $MODKEY-Return
		eval $WMII_TERM &
	Key SMODKEYShift-space
		wmiir xwrite /tag/sel/ctl send sel toggle
	Key SMODKEYf
		wmiir xwrite /client/sel/ctl Fullscreen toggle
	Key SMODKEYShift-c
		wmiir xwrite /client/sel/ctl kill
	Key SMODKEYShift-t
		wmiir xwrite "/client/$(wmiir read /client/sel/ctl)/tags" "$(tagsmenu)" &
	Key SMODKEY$LEFT
		wmiir xwrite /tag/sel/ctl select left
	Key SMODKEY$RIGHT
		wmiir xwrite /tag/sel/ctl select right
	Key SMODKEY$DOWN
		wmiir xwrite /tag/sel/ctl select down
	Key SMODKEY$UP
		wmiir xwrite /tag/sel/ctl select up
	Key SMODKEYShift-$LEFT
		wmiir xwrite /tag/sel/ctl send sel left
	Key SMODKEYShift-$RIGHT
		wmiir xwrite /tag/sel/ctl send sel right
	Key SMODKEYShift-$DOWN
		wmiir xwrite /tag/sel/ctl send sel down
	Key SMODKEYShift-$UP
		wmiir xwrite /tag/sel/ctl send sel up
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		cat <<!
	Key SMODKEY$i
		wmiir xwrite /ctl view "$i"
	Key SMODKEYShift-$i
		wmiir xwrite /client/sel/tags "$i"
!
	done
}

# WM Configuration
wmiir write /ctl << EOF
font $WMII_FONT
focuscolors $WMII_FOCUSCOLORS
normcolors $WMII_NORMCOLORS
grabmod $MODKEY
border 1
EOF

export WMII_MENU WMII_9MENU WMII_FONT WMII_TERM
export WMII_FOCUSCOLORS WMII_SELCOLORS WMII_NORMCOLORS WMII_CMDNORMCOLORS
# Feed events to `wmiiloop' for processing
eval "$(eventstuff | sed 's/SMODKEY/$MODKEY-/g' |  sed 's/^[	]//' | { . wmiiloop; })"
echo "$(eventstuff | sed 's/SMODKEY/$MODKEY-/g' |  sed 's/^[	]//' | { . wmiiloop; })"
Keys1="$Keys Menu"
Keys=""
echo "$Keys1" | tr ' ' '\n' | wmiir write /keys

eval "$(eventstuff | sed 's/SMODKEY//g' |  sed 's/^[	]//' | { . wmiiloop; })"
echo "$(eventstuff | sed 's/SMODKEY//g' |  sed 's/^[	]//' | { . wmiiloop; })"
Keys2="$Keys1 $Keys Menu a b c d e f g h i j k l m n o p q r s t u v w x y z / ; ' [ ] ( ) - + = Mod4"
echo "$Keys2" | tr ' ' '\n' | wmiir write /keys
MODE=0
Key_Menu() {

if [ $MODE = "1" ]; then
	MODE=0
	echo "indeed... should change colors::"
	echo "$Keys2" | tr ' ' '\n' | wmiir write /keys
	echo "$WMII_CMDNORMCOLORS" | wmiir create /rbar/status
	#echo "$WMII_FOCUSCOLORS" | wmiir create /rbar/status
else
	MODE=1
	echo "$Keys1" | tr ' ' '\n' | wmiir write /keys
	echo "$WMII_NORMCOLORS" | wmiir create /rbar/status
fi
echo $MODE
}


Key_i() {
	echo "$Keys1" | tr ' ' '\n' | wmiir write /keys
	echo "$WMII_NORMCOLORS" | wmiir create /rbar/status
}

# Functions
Action() {
	action=$1; shift
	if [ -n "$action" ]; then
		Action_$action "$@" \
		|| conf_which $action "$@"
	fi
}

proglist() {
	paths=$(echo "$@" | sed 'y/:/ /')
	ls -lL $paths 2>/dev/null \
		| awk '$1 ~ /^[^d].*x/ && NF > 2 { print $NF }' \
		| sort | uniq
}

# Misc
progsfile="$WMII_NS_DIR/.proglist"
Action status &
proglist $PATH >$progsfile &

xsetroot -solid "$WMII_BACKGROUND" &

# Setup Tag Bar
seltag="$(wmiir read /tag/sel/ctl 2>/dev/null)"
wmiir ls /lbar |
while read bar; do
	wmiir remove "/lbar/$bar"
done
wmiir ls /tag | sed -e 's|/||; /^sel$/d' |
while read tag; do
	if [ "X$tag" = "X$seltag" ]; then
		echo "$WMII_FOCUSCOLORS" "$tag" | wmiir create "/lbar/$tag" 
	else
		echo "$WMII_NORMCOLORS" "$tag" | wmiir create "/lbar/$tag"
	fi
done

# More functions
tagsmenu() {
        wmiir ls /tag | sed 's|/||; /^sel$/d' | eval $WMII_MENU
}

actionlist() {
	{	proglist $WMII_CONFPATH
		echo -n $Actions | tr ' ' '\012'
	} | sort | uniq
}

conf_which() {
	which=$(which which)
	prog=$(PATH="$WMII_CONFPATH" $which $1); shift
	[ -n "$prog" ] && $prog "$@"
}

# Stop any running instances of wmiirc
echo Start wmiirc | wmiir write /event || exit 1

wmiir read /event |
while read event; do
	set -- $event
	event=$1; shift
	Event_$event $@
done 2>/dev/null
